### ISSUE TITLE
Plugin broken since Trailblazer Reloaded Leagues release.

### ISSUE THREAD

**Issue by Repr0t** [neeerp/runelite-random-screenshot#8]
No longer taking screenshots at any interval.
Custom directory no longer works, either.
Stopped working practically the same day Trailblazer Reloaded released.
(Also didn't get any random screenshots of the league account during that time, either)

**Comment by neeerp** [comment]
I'll try to take a look in the evening today...

Do you know if the custom directory feature was working before trailblazer came out?

**Comment by neeerp** [comment]
I've fixed the plugin and now just need to get it merged into plugin hub...

**Comment by neeerp** [comment]
Just checked now by running Runelite from my local install (as opposed to my dev environment), and the plugin appears to be working again. Please let me know if you're still noticing issues!
